name: Update Python Dependencies

on:
  schedule:
    - cron: '0 4 * * SUN'   # every Sunday at 04:00 UTC
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Compile requirements.in → requirements.txt
        run: |
          pip-compile requirements.in --output-file=requirements.txt

      - name: Commit & create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 🔄 chore: update dependencies
          branch: chore/update-dependencies
          title: chore: update dependencies
          labels: dependencies
